#!/usr/bin/env bash
# =============================================================================
# ITMP — Full Installation Script
# Tested on Ubuntu 22.04 / 24.04 LTS
#
# Usage:
#   chmod +x setup/install.sh
#   sudo ./setup/install.sh
# =============================================================================

set -euo pipefail

# ── Colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
die()     { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# ── Must run as root ──────────────────────────────────────────────────────────
[[ $EUID -eq 0 ]] || die "Run this script with sudo: sudo ./setup/install.sh"

# ── Detect project root (directory containing setup/) ────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

NODE_SERVER_DIR="$PROJECT_ROOT/back-end/node-server"
PYTHON_SCRIPTS_DIR="$PROJECT_ROOT/back-end/scripting/python-scripts"
SCHEMA_FILE="$PROJECT_ROOT/back-end/scripting/mysql-scripts/schema.sql"
NGINX_CONF_SRC="$SCRIPT_DIR/nginx.conf"
NGINX_SITE_FILE="/etc/nginx/sites-available/itmp"
FRONTEND_ROOT="$PROJECT_ROOT/front-end"
STORAGE_DIR="$NODE_SERVER_DIR/storage"
ENV_FILE="$NODE_SERVER_DIR/.env"
LOG_DIR="$PROJECT_ROOT/logs"

echo ""
echo -e "${CYAN}══════════════════════════════════════════════════════════${NC}"
echo -e "${CYAN}   ITMP — Intelligent Talent Matching Platform Setup      ${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════════════${NC}"
echo ""
info "Project root: $PROJECT_ROOT"
echo ""

# ── Prompt for database password ──────────────────────────────────────────────
read -rsp "Enter MySQL root password to set (press Enter to use 'root'): " DB_PASS
echo ""
DB_PASS="${DB_PASS:-root}"
DB_NAME="itmp_db"
DB_USER="root"

# ── 1. Update package list ────────────────────────────────────────────────────
info "Updating package lists…"
apt-get update -qq
success "Package lists updated."

# ── 2. Install system packages ────────────────────────────────────────────────
info "Installing system packages (nginx, mysql-server, python3, curl)…"
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
    nginx \
    mysql-server \
    python3 \
    python3-venv \
    python3-pip \
    curl \
    git \
    build-essential
success "System packages installed."

# ── 3. Install Node.js 20 LTS via NodeSource ─────────────────────────────────
if ! command -v node &>/dev/null || [[ "$(node --version | cut -d. -f1 | tr -d 'v')" -lt 18 ]]; then
    info "Installing Node.js 20 LTS…"
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - >/dev/null 2>&1
    apt-get install -y -qq nodejs
    success "Node.js $(node --version) installed."
else
    success "Node.js $(node --version) already installed."
fi

# ── 4. Configure MySQL ────────────────────────────────────────────────────────
info "Starting MySQL service…"
systemctl enable mysql --quiet
systemctl start mysql

info "Securing MySQL and creating database…"

# Set root password and create the database/schema
mysql -u root --connect-expired-password 2>/dev/null <<EOF
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${DB_PASS}';
FLUSH PRIVILEGES;
EOF

mysql -u root -p"${DB_PASS}" 2>/dev/null < "$SCHEMA_FILE" \
    && success "Database '${DB_NAME}' and schema applied." \
    || warn "Schema may already be applied — skipping."

# ── 5. Write .env for Node server ────────────────────────────────────────────
info "Writing .env file for Node server…"
cat > "$ENV_FILE" <<EOF
# ITMP Node Server — environment variables
# Generated by setup/install.sh

DB_HOST=localhost
DB_USER=${DB_USER}
DB_PASS=${DB_PASS}
DB_NAME=${DB_NAME}
PORT=3000
EOF
chmod 600 "$ENV_FILE"
success ".env written to $ENV_FILE"

# ── 6. Install Node.js dependencies ──────────────────────────────────────────
info "Installing Node.js dependencies (npm install)…"
cd "$NODE_SERVER_DIR"
npm install --silent
success "Node.js dependencies installed."

# ── 7. Create upload storage directories ─────────────────────────────────────
info "Creating storage directories…"
mkdir -p "$STORAGE_DIR/resumes" "$STORAGE_DIR/avatars" "$LOG_DIR"
# Allow the web server / node process to write here
chown -R www-data:www-data "$STORAGE_DIR" 2>/dev/null || true
chmod -R 775 "$STORAGE_DIR"
success "Storage directories created at $STORAGE_DIR"

# ── 8. Set up Python venv for resume scanner ─────────────────────────────────
VENV_DIR="$PYTHON_SCRIPTS_DIR/venv"
if [[ ! -d "$VENV_DIR" ]]; then
    info "Creating Python virtual environment…"
    python3 -m venv "$VENV_DIR"
    "$VENV_DIR/bin/pip" install --upgrade pip --quiet
    "$VENV_DIR/bin/pip" install spacy pdfminer.six --quiet
    "$VENV_DIR/bin/python" -m spacy download en_core_web_sm --quiet
    success "Python venv created and dependencies installed."
else
    success "Python venv already exists — skipping."
fi

# ── 9. Configure nginx ────────────────────────────────────────────────────────
info "Configuring nginx…"

# Write the nginx site config with the actual project path substituted in
sed "s|__FRONTEND_ROOT__|${FRONTEND_ROOT}|g" "$NGINX_CONF_SRC" > "$NGINX_SITE_FILE"

# Enable site, disable default
ln -sf "$NGINX_SITE_FILE" /etc/nginx/sites-enabled/itmp
rm -f /etc/nginx/sites-enabled/default

nginx -t -q && systemctl restart nginx
success "nginx configured and restarted."

# ── 10. Make helper scripts executable ───────────────────────────────────────
info "Making setup scripts executable…"
chmod +x "$SCRIPT_DIR/server.sh"
chmod +x "$PROJECT_ROOT/back-end/scripting/bash-scripts/"*.sh 2>/dev/null || true
success "Scripts are executable."

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}   Installation complete!                                  ${NC}"
echo -e "${GREEN}══════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  Start the backend:  ${CYAN}./setup/server.sh start${NC}"
echo -e "  Stop the backend:   ${CYAN}./setup/server.sh stop${NC}"
echo -e "  View logs:          ${CYAN}./setup/server.sh logs${NC}"
echo -e "  Open in browser:    ${CYAN}http://localhost${NC}"
echo ""
echo -e "  .env file:          ${CYAN}${ENV_FILE}${NC}"
echo -e "  nginx config:       ${CYAN}${NGINX_SITE_FILE}${NC}"
echo -e "  MySQL database:     ${CYAN}${DB_NAME}${NC} (user: ${DB_USER})"
echo ""
